name: ios_fastlane_tests
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  tests:
    name: ios_fastlane_tests
    runs-on: macos-latest
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.5'
    
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
        bundler-cache: true

    - shell: bash
      env:
          TELNYX_SIP_USER: ${{ secrets.TELNYX_SIP_USER }}
          TELNYX_SIP_PASSWORD: ${{ secrets.TELNYX_SIP_PASSWORD }}
          TELNYX_SIP_TOKEN: ${{ secrets.TELNYX_SIP_TOKEN }}
      run:  |
          sh scripts/setup_env.sh -u "$TELNYX_SIP_USER" -p "$TELNYX_SIP_PASSWORD" -t "$TELNYX_SIP_TOKEN"
          
    - name: Setup Fastlane
      run:  |
          bundle install
    - name: Install Pods
      run:  |
        pod install
    - name: Sleep for 10 seconds
      run: |
        sleep 10
    - name: Run tests 
      run: |
        bundle exec fastlane tests
