name: ios_fastlane
on:
  push:
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  tests:
    name: Fastlane 
    runs-on: macos-latest
      
    steps:      
    - name: Checkout
      uses: actions/checkout@v2
    - name: Select Xcode Version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '12.2'
    
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.3
        bundler-cache: true

    - name: Set environment variables for testing
      run:  |
          export TELNYX_SIP_USER=${{ secrets.TELNYX_SIP_USER }}
          export TELNYX_SIP_PASSWORD=${{ secrets.TELNYX_SIP_PASSWORD }}
          export TELNYX_SIP_TOKEN=${{ secrets.TELNYX_SIP_TOKEN }}
          printenv
          
    - name: Setup Fastlane
      run:  |
          bundle install
    - name: Install Pods
      run:  |
        pod install
    - name: Sleep for 20 seconds
      run: |
        sleep 20
    - name: Run tests 
      run: |
        bundle exec fastlane tests        
    - name: Run Swift lint 
      run: |
        bundle exec fastlane lint
